"""empty message

Revision ID: 9368d04a2b5f
Revises: c1e6f14ac4a2
Create Date: 2020-04-02 08:48:36.405318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9368d04a2b5f'
down_revision = 'c1e6f14ac4a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_tags',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_tags')
    # ### end Alembic commands ###
